# Script for generating instructions for automated dilution before library prep
#Acts specifically on .txt files output by Software Max Pro. 

#Process .txt file generated by plate reader. 

#0. Identify most recent file. 
#First search for files that start with 'qubit' and end with '.txt'
#Then call file properties, and choose the 'max' date modified time (mtime)
qubitfiles <- list.files()[grep("^qubit.*txt$", list.files())] 
properties <- file.info(qubitfiles)
file <- rownames(properties)[which.max(properties$mtime)] 

#Input .txt file here if desired
#raw <- read.table("20200727_162222 Labware 1_1.txt", fill = TRUE, fileEncoding = "UTF-16")
raw <- read.table(file, fill = TRUE, fileEncoding = "UTF-16") 
raw <- raw[-1,-1]
raw <- raw[1:2,]
colnames(raw) <- raw[1,]
#1. Plot regression line with calibration (always decreasing C12 to H12)
calibration <- as.vector(t(as.integer(raw[2,c("A12","B12", "C12", "D12", "E12", "F12", "G12", "H12")])))
concentrations <- c(10, 5, 5/2, 5/4, 5/8, 5/16, 5/32, 5/64 ) #5 µL of 10 ng/µL into 100 µL, halving dilution series.
cal_line <- lm(concentrations ~ calibration)

test <- calibration*coefficients(cal_line)[2] + coefficients(cal_line)[1]
summary(cal_line)
print(test)

#3. Return matrix as a list, and reorder
samples <- (t(raw))
reorder <- seq(1,96,12)
for (i in 2:12){reorder <- append(reorder, seq(i,96,12))}
samples <- (samples[reorder,])
samples <- as.data.frame(samples[,-1])
colnames(samples) <- "Platereader"
samples$Platereader <- as.integer(samples$Platereader)

#4. Convert using calibration line, remove wells with background noise
samples$Concentration <- samples$Platereader*coefficients(cal_line)[2]+ coefficients(cal_line)[1]
for (i in 1:nrow(samples)){
  if (samples$Platereader[i]<500000){samples$Concentration[i] <- 0}}

samples$converted_conc <- round(samples$Concentration*1, digits=3)
#5. Use 5 µL for dilution into 0.2 ng/µL 

vol_for_dilution <- 5
desired_conc <- 0.25 
samples$`Vol. to 5uL` <- round((samples$converted_conc*vol_for_dilution/desired_conc)-vol_for_dilution,digits=0)

#6. Final check on pipetting volume
samples$Check <- 1000 
for (i in 1:nrow(samples)){
if (samples[i,4]>1000){samples[i,5] <- 0}
  if (samples[i,4]<200& samples[i,4]>0){samples[i,5] <- 200}
  if (samples[i,4]<50 & samples[i,4]>0){samples[i,5] <- 50}
  if (samples[i,4]==-5){samples[i,5] <- 0}}

#7. Label columns and include column for Biomek
#colnames(samples) <- c("Sample", "Well", "Signal", "Conc. measured", 
                       #"Stock soln", "Vol. to 5uL", "Check")
samples$"Partition" <- 2

#8. Split csv into 1000 and 200 uL pipetting tasks: 
samples_1000 <- samples[which(samples[1:88,5] == 1000),]
samples_200 <- samples[which(samples[1:88,5] == 200),]
samples_50 <- samples[which(samples[1:88,5] == 50),]
samples_combined <- rbind(samples_50, samples_200)

samples$file <- file

#9. Export
write.csv(samples, "allsamples.csv")
write.csv(samples_1000,"samples_1000.csv")
write.csv(samples_200,"samples_200.csv")
write.csv(samples_50,"samples_50.csv")
write.csv(samples_combined,"samples_combined.csv")

